version: '3.9'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 9980:9980
      - 443:443
    depends_on:
      - mysql

